import { actionsType } from '../../types'
export const buttons:actionsType[] = [
    {
        text:'technology',
        color:'#3376F7'
    },
    {
        text:'science',
        color:'#179843'
    },
    {
        text:'finance',
        color:'#EF3A3D'
    },
    {
        text:'society',
        color:'#E6A900'
    },
    {
        text:'entertainment',
        color:'#D7246E'
    },
    {
        text:'health',
        color:'#17AE9D'
    },
    {
        text:'history',
        color:'#F76715'
    },
    {
        text:'news',
        color:'#8251F6'
    },
]
